FROM php:fpm

RUN apt-get update
RUN apt-get install -y  git-all \
                        zlib1g-dev

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN docker-php-ext-install pdo \
                           pdo_mysql \
                           zip