FROM php:7.4-fpm

RUN apt-get update
RUN apt-get install -y  git-all \
                        libzip-dev \
                        zip

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN docker-php-ext-install pdo \
                           pdo_mysql \
                           zip